basePath: /
definitions:
  api.CreateMedia:
    properties:
      title:
        example: Sheep Discovers How To Use A Trampoline
        type: string
    required:
    - title
    type: object
  api.FileFormat:
    properties:
      bit_rate:
        type: string
      duration:
        example: "0"
        type: string
      filename:
        type: string
      format_long_name:
        type: string
      format_name:
        type: string
      nb_programs:
        type: integer
      nb_streams:
        type: integer
      probe_score:
        type: integer
      size:
        type: string
      start_time:
        example: "0"
        type: string
    type: object
  api.HealthCheckResponse:
    properties:
      commit:
        type: string
      tag:
        type: string
    type: object
  api.UpdateMedia:
    properties:
      title:
        example: Sheep Discovers How To Use A Trampoline
        type: string
    required:
    - title
    type: object
  dialect.Driver:
    type: object
  ent.Media:
    properties:
      created_at:
        description: CreatedAt holds the value of the "created_at" field.
        type: string
      edges:
        $ref: '#/definitions/ent.MediaEdges'
        description: |-
          Edges holds the relations/edges for other nodes in the graph.
          The values are being populated by the MediaQuery when eager-loading is set.
        type: object
      id:
        description: ID of the ent.
        type: string
      status:
        description: Status holds the value of the "status" field.
        type: string
      title:
        description: Title holds the value of the "title" field.
        type: string
      updated_at:
        description: UpdatedAt holds the value of the "updated_at" field.
        type: string
    type: object
  ent.MediaEdges:
    properties:
      media_files:
        description: MediaFiles holds the value of the media_files edge.
        items:
          $ref: '#/definitions/ent.MediaFile'
        type: array
    type: object
  ent.MediaFile:
    properties:
      created_at:
        description: CreatedAt holds the value of the "created_at" field.
        type: string
      duration_seconds:
        description: DurationSeconds holds the value of the "duration_seconds" field.
        type: number
      edges:
        $ref: '#/definitions/ent.MediaFileEdges'
        description: |-
          Edges holds the relations/edges for other nodes in the graph.
          The values are being populated by the MediaFileQuery when eager-loading is set.
        type: object
      encoder_preset:
        description: EncoderPreset holds the value of the "encoder_preset" field.
        type: string
      framerate:
        description: Framerate holds the value of the "framerate" field.
        type: integer
      id:
        description: ID of the ent.
        type: string
      media_type:
        description: MediaType holds the value of the "media_type" field.
        type: string
      scaled_width:
        description: ScaledWidth holds the value of the "scaled_width" field.
        type: integer
      updated_at:
        description: UpdatedAt holds the value of the "updated_at" field.
        type: string
      video_bitrate:
        description: VideoBitrate holds the value of the "video_bitrate" field.
        type: integer
    type: object
  ent.MediaFileEdges:
    properties:
      media:
        $ref: '#/definitions/ent.Media'
        description: Media holds the value of the media edge.
        type: object
    type: object
  util.DataResponse:
    properties:
      code:
        example: 200
        type: integer
      data:
        type: object
    type: object
  util.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: demo-v1.gilfoyle.dreamvo.com
info:
  contact: {}
  description: Cloud-native media hosting & streaming server for businesses.
  license:
    name: GNU General Public License v3.0
    url: https://github.com/dreamvo/gilfoyle/blob/master/LICENSE
  title: Gilfoyle server
  version: v1
paths:
  /healthz:
    get:
      description: Check for the health of the service
      operationId: checkHealth
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.HealthCheckResponse'
              type: object
      summary: Check service status
      tags:
      - Instance
  /medias:
    get:
      description: Get latest created medias
      operationId: getAllMedias
      parameters:
      - description: Max number of results
        in: query
        name: limit
        type: integer
      - description: Number of results to ignore
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/ent.Media'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Query medias
      tags:
      - Medias
    post:
      consumes:
      - application/json
      description: Create a new media
      operationId: createMedia
      parameters:
      - description: Media data
        in: body
        name: media
        required: true
        schema:
          $ref: '#/definitions/api.CreateMedia'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/ent.Media'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Create a media
      tags:
      - Medias
  /medias/{id}:
    delete:
      description: Delete one media
      operationId: deleteMedia
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.DataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Delete a media
      tags:
      - Medias
    get:
      description: Get one media
      operationId: getMedia
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/ent.Media'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Get a media
      tags:
      - Medias
    patch:
      consumes:
      - application/json
      description: Update an existing media
      operationId: updateMedia
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: string
      - description: Media data
        in: body
        name: media
        required: true
        schema:
          $ref: '#/definitions/api.UpdateMedia'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/ent.Media'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Update a media
      tags:
      - Medias
  /medias/{id}/upload/audio:
    post:
      consumes:
      - multipart/form-data
      description: Upload a new audio file for a given media ID
      operationId: uploadAudio
      parameters:
      - description: Media identifier
        in: path
        name: id
        required: true
        type: string
      - description: Audio file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.FileFormat'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Upload a audio file
      tags:
      - Medias
  /medias/{id}/upload/video:
    post:
      consumes:
      - multipart/form-data
      description: Upload a new video file for a given media ID
      operationId: uploadVideo
      parameters:
      - description: Media identifier
        in: path
        name: id
        required: true
        type: string
      - description: Video file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.FileFormat'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Upload a video file
      tags:
      - Medias
  /medias/{media_id}/attachments:
    get:
      description: Get attachments of a media
      operationId: getMediaAttachments
      parameters:
      - description: Media identifier
        in: path
        name: media_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.DataResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Get attachments of a media
      tags:
      - Attachments
    post:
      consumes:
      - multipart/form-data
      description: Add attachment to a media
      operationId: addMediaAttachment
      parameters:
      - description: Media identifier
        in: path
        name: media_id
        required: true
        type: string
      - description: Attachment file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.DataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Add attachment to a media
      tags:
      - Attachments
  /medias/{media_id}/attachments/{key}:
    delete:
      description: Delete attachment of a media
      operationId: deleteMediaAttachment
      parameters:
      - description: Media identifier
        in: path
        name: media_id
        required: true
        type: string
      - description: Attachment unique identifier
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.DataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Delete attachment of a media
      tags:
      - Attachments
  /medias/{media_id}/stream/{preset}:
    get:
      description: Get stream from media file
      operationId: streamMedia
      parameters:
      - description: Media identifier
        in: path
        name: media_id
        required: true
        type: string
      - description: Encoder preset
        in: path
        name: preset
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              description: application/octet-stream
              type: string
          schema:
            $ref: '#/definitions/util.DataResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Get stream from media file
      tags:
      - Stream
  /metricsz:
    get:
      description: Get metrics about this Gilfoyle instance
      operationId: getMetrics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.DataResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Get instance metrics
      tags:
      - Instance
schemes:
- http
- https
swagger: "2.0"
